packages:
  - .dsh/plugins/*
  - desktop

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  electron: true
  electron-winstaller: true
  koffi: true
  node-pty: true
  protobufjs: true
